[package]
name = "frida-deepfreeze-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
frida = { version = "0.4.0", features = ["auto-download"] }
frida-sys = { version = "0.4.0", features = ["auto-download", "frida-build"] }
lazy_static = "1.4.0"

# [target.'cfg(unix)'.dependencies]
ctor = "0.2.0"

# [target.'cfg(windows)'.dependencies]
# winapi = "0.3.9"
