name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests - frida
      run: cargo test --verbose

    # - name: Run tests - frida
    #   if: matrix.os == 'windows-latest'
    #   run: cargo test --verbose --no-default-features --features managed_lib
